import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
  },
  photoBox: {
    backgroundColor: '#F6F6F6',
    width: 343,
    height: 240,
    marginTop: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  camera: {
    width: 343,
    height: 240,
    marginHorizontal: 16,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerWrapper: {
    justifyContent: 'flex-end',
    alignItems: 'center',
    height: 88,
    borderBottomWidth: 1,
    borderBottomColor: '#BDBDBD',
  },
  headerText: {
    marginBottom: 11,
    fontSize: 17,
  },
  icon: {
    width: 60,
    height: 60,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 50,
    zIndex: 1,
  },
  previewPhotoContainer: {
    position: 'absolute',
    marginTop: 32,
    marginHorizontal: 16,
  },
  previewPhoto: {
    height: 240,
    width: '100%',
    borderRadius: 8,
  },
  text: {
    color: '#BDBDBD',
  },
  input: {
    marginTop: 32,
    borderBottomWidth: 1,
    borderBottomColor: '#E8E8E8',
    paddingBottom: 8,
  },
  button: {
    marginTop: 32,
    backgroundColor: '#F6F6F6',
    height: 61,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonActive: {
    marginTop: 32,
    backgroundColor: '#FF6C00',
    height: 61,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText: {
    color: '#BDBDBD',
  },
  buttonTextActive: {
    color: '#fff',
  },
  trashBtn: {
    marginTop: 'auto',
    alignSelf: 'center',
  },
  locationContainer: {
    // flex: 1,
    flexDirection: 'row',
    // justifyContent: 'center',
    alignItems: 'center',
    // backgroundColor: '#fff',
  },
  locationInput: {
    // flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    // backgroundColor: '#E8E8E8',
    marginTop: 32,
    borderBottomWidth: 1,
    borderBottomColor: '#E8E8E8',
    paddingBottom: 8,
    // flex: 1,
    // paddingTop: 10,
    // paddingRight: 10,
    // paddingBottom: 10,
    // paddingLeft: 0,
    // backgroundColor: '#fff',
    // color: '#424242',
  },
});
